# Generated by Django 5.0.1 on 2024-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_fav_foods_alter_profile_fav_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='category',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=30),
        ),
    ]
