# Generated by Django 5.0.1 on 2024-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='category',
            field=models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='H', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
