# Generated by Django 5.0.1 on 2024-01-26 15:33

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_category_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='category',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_to),
        ),
    ]
