# Generated by Django 5.0.1 on 2024-01-10 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('background_pic', models.FileField(upload_to='')),
                ('icon', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('DS', 'Dessert'), ('FI', 'Fish'), ('IT', 'Italian'), ('AS', 'Asian'), ('BU', 'Burger'), ('PI', 'Pizza'), ('CH', 'Chicken')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('arrival_time', models.IntegerField(default=0)),
                ('open_time', models.TimeField()),
                ('dine_in', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('price_rating', models.IntegerField(default=1)),
                ('features', models.ManyToManyField(to='restaurant.restaurantfeature')),
            ],
        ),
    ]
