# Generated by Django 5.0.1 on 2024-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('AS', 'Asian'), ('DS', 'Dessert'), ('CH', 'Chicken'), ('IT', 'Italian'), ('FI', 'Fish'), ('BU', 'Burger'), ('PI', 'Pizza')], max_length=30),
        ),
    ]
