# Generated by Django 5.0.1 on 2024-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('FI', 'Fish'), ('PI', 'Pizza'), ('IT', 'Italian'), ('CH', 'Chicken'), ('BU', 'Burger'), ('AS', 'Asian'), ('DS', 'Dessert')], max_length=30),
        ),
    ]
