# Generated by Django 5.0.1 on 2024-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('DS', 'Dessert'), ('BU', 'Burger'), ('CH', 'Chicken'), ('PI', 'Pizza'), ('FI', 'Fish'), ('IT', 'Italian'), ('AS', 'Asian')], max_length=30),
        ),
    ]
