# Generated by Django 5.0.1 on 2024-01-10 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('category', models.CharField(choices=[('DS', 'Dessert'), ('FI', 'Fish'), ('IT', 'Italian'), ('AS', 'Asian'), ('BU', 'Burger'), ('PI', 'Pizza'), ('CH', 'Chicken')], default='AS', max_length=30)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('prepare_time', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
