# Generated by Django 5.0.1 on 2024-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('AS', 'Asian'), ('BU', 'Burger'), ('PI', 'Pizza'), ('IT', 'Italian'), ('DS', 'Dessert'), ('FI', 'Fish'), ('CH', 'Chicken')], default='AS', max_length=30),
        ),
    ]
