# Generated by Django 5.0.1 on 2024-01-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('PI', 'Pizza'), ('FI', 'Fish'), ('AS', 'Asian'), ('DS', 'Dessert'), ('BU', 'Burger'), ('CH', 'Chicken'), ('IT', 'Italian')], default='AS', max_length=30),
        ),
    ]
