# Generated by Django 5.0.1 on 2024-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('AS', 'Asian'), ('CH', 'Chicken'), ('DS', 'Dessert'), ('IT', 'Italian'), ('FI', 'Fish'), ('BU', 'Burger'), ('PI', 'Pizza')], default='AS', max_length=30),
        ),
    ]
