# Generated by Django 5.0.1 on 2024-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_picture_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('PI', 'Pizza'), ('FI', 'Fish'), ('IT', 'Italian'), ('CH', 'Chicken'), ('BU', 'Burger'), ('AS', 'Asian'), ('DS', 'Dessert')], default='AS', max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
