# Generated by Django 5.0.1 on 2024-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('CH', 'Chicken'), ('DS', 'Dessert'), ('FI', 'Fish'), ('AS', 'Asian'), ('BU', 'Burger'), ('IT', 'Italian'), ('PI', 'Pizza')], default='AS', max_length=30),
        ),
    ]
