# Generated by Django 5.0.1 on 2024-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a9c9584d87c54503883cb0a64bdebd30', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UC', 'UpComing'), ('CN', 'Canceled'), ('CP', 'Complete')], default='UC', max_length=500),
        ),
    ]
