# Generated by Django 5.0.1 on 2024-01-23 22:58

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=order.models.create_order_number, editable=False, max_length=100),
        ),
    ]
