# Generated by Django 5.0.1 on 2024-01-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_prepare_foods',
            field=models.IntegerField(default=0),
        ),
    ]
