# Generated by Django 5.0.1 on 2024-01-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CP', 'Complete'), ('UC', 'UpComing'), ('CN', 'Canceled')], default='UC', max_length=500),
        ),
    ]
